src/__init__.py
from flask      import Flask
from src.config import Config

# Init Flask app using config.
app = Flask(__name__)
app.config.from_object(Config)


from src.routes        import api
from src.CassandraConn import CassandraConn

app.register_blueprint(api)

# Connect to Cassandra db
app.db = CassandraConn(
    hosts    = Config.CASSANDRA_HOSTS,
    keyspace = Config.CASSANDRA_KEYSPACE
)

src/routes.py
from flask import jsonify, Blueprint, render_template, request
from src   import app


api = Blueprint("api", __name__, url_prefix="/")


# All routes are test functions at the moment, mostly for testing
# functionality and connectivity between server and Cassandra node(s).
@api.route("/",      methods=['GET'], strict_slashes=False)
@api.route("/index", methods=['GET'], strict_slashes=False)
def index() :
    return render_template("home.html")


@api.route("/getUsers", methods=['GET'], strict_slashes=False)
def getUsers() :
    out_dic = {}

    for p in app.db.getTable("person") :
        out_dic[str(p.user_id)] = {"name" : f"{p.fname} {p.lname}", "role" : p.role}

    return jsonify(out_dic)


@api.route("/getMovie", methods=['GET', 'POST'], strict_slashes=False)
def getMovie() :
    out_dic = {}
    if request.method == "POST" :
        movie_name = request.form['movie_name']
        for m in app.db.getMovie(movie_name):
            out_dic[m.title] = {"year": m.year, "director": m.director}
        return jsonify(out_dic)

    return render_template("get_movie.html")

@api.route("/getPerson", methods=['GET', 'POST'], strict_slashes=False)
def getPerson() :
    out_dic = {}
    if request.method == "POST" :
        fname = request.form['fname']
        lname = request.form['lname']
        for p in app.db.getPerson(fname,lname):
            out_dic[str(p.user_id)] = {"name" : f"{p.fname} {p.lname}", "role" : p.role}
        return jsonify(out_dic)

    return render_template("get_person.html")

@api.route("/getMovies", methods=['GET'], strict_slashes=False)
def getMovies() :
    out_dic = {}
    for m in app.db.getTable("movie") :
        out_dic[m.title] = {"year" : m.year, "director" : m.director}

    return jsonify(out_dic)


@api.route("/createPerson", methods=['GET', 'POST'], strict_slashes=False)
def createPerson() :
    if request.method == "POST" :
        fname = request.form['fname']
        lname = request.form['lname']
        role  = request.form['role']

        app.db.createPerson(fname, lname, role)
        return render_template("home.html")

    return render_template("create_person.html")


@api.route("/createMovie", methods=['GET', 'POST'], strict_slashes=False)
def createMovie() :
    if request.method == "POST" :
        movie_name = request.form['movie_name']
        director   = request.form['director']
        year       = int(request.form['year'])

        app.db.createMovie(movie_name, director, year)
        return render_template("home.html")

    return render_template("create_movie.html")

@api.route("/removePerson", methods=['GET', 'POST'], strict_slashes=False)
def removePerson() :
    out_dic = {}
    if request.method == "POST" :
        fname = request.form['fname']
        lname = request.form['lname']
        app.db.removePerson(fname,lname)
        return render_template("home.html")

    return render_template("remove_person.html")

@api.route("/removeMovie", methods=['GET', 'POST'], strict_slashes=False)
def removeMovie() :
    out_dic = {}
    if request.method == "POST" :
        movie_name = request.form['movie_name']
        app.db.removeMovie(movie_name)
        return render_template("home.html")

    return render_template("remove_movie.html")

src/templates/create_movie.html
<form action="{{ url_for('api.createMovie') }}" method="post">
    <label for="movie_name">Movie Name:</label><br>
    <input type="text" id="movie_name" name="movie_name"><br>

    <label for="director">Director's Name:</label><br>
    <input type="text" id="director" name="director"><br>

    <label for="year">Year:</label><br>
    <input type="text" id="year" name="year"><br>

    <input type="submit">
</form>

src/templates/create_person.html
<form action="{{ url_for('api.createPerson') }}" method="post">
    <label for="fname">First Name:</label><br>
    <input type="text" id="fname" name="fname"><br>

    <label for="lname">Last Name:</label><br>
    <input type="text" id="lname" name="lname"><br>

    <label for="role">Role:</label><br>
    <input type="text" id="role" name="role"><br>

    <input type="submit">
</form>

src/templates/get_movie.html
<form action="{{ url_for('api.getMovie') }}" method="post">
    <label for="movie_name">Movie Name:</label><br>
    <input type="text" id="movie_name" name="movie_name"><br>
    <input type="submit">
</form>

src/templates/get_person.html
<form action="{{ url_for('api.getPerson') }}" method="post">
    <label for="fname">First Name:</label><br>
    <input type="text" id="fname" name="fname"><br>

    <label for="lname">Last Name:</label><br>
    <input type="text" id="lname" name="lname"><br>
    <input type="submit">
</form>

src/templates/home.html
<!DOCTYPE html>
<html>
    <body>
        <h1>Indie Movie Database</h1>
        <h2>Create and View Movies and their actors, directors, etc.:</h2>
        <ul>
          <li><a href="{{ url_for('api.createPerson') }}">Create Person</a></li>
          <li><a href="{{ url_for('api.createMovie') }}" >Create Movie</a></li>
            <li><a href="{{ url_for('api.getMovie') }}"   >Look For a Movie</a></li>
            <li><a href="{{ url_for('api.getPerson') }}"   >Look For a Person</a></li>
            <li><a href="{{ url_for('api.removeMovie') }}"   >Remove a Movie</a></li>
            <li><a href="{{ url_for('api.removePerson') }}"   >Remove a Person</a></li>
          <li><a href="{{ url_for('api.getUsers') }}"    >View All People</a></li>
          <li><a href="{{ url_for('api.getMovies') }}"   >View All Movies</a></li>
        </ul>  
    </body>
</html>

src/templates/remove_movie.html
<form action="{{ url_for('api.removeMovie') }}" method="post">
    <label for="movie_name">Movie Name:</label><br>
    <input type="text" id="movie_name" name="movie_name"><br>
    <input type="submit">
</form>

src/templates/remove_person.html
<form action="{{ url_for('api.removePerson') }}" method="post">
    <label for="fname">First Name:</label><br>
    <input type="text" id="fname" name="fname"><br>

    <label for="lname">Last Name:</label><br>
    <input type="text" id="lname" name="lname"><br>
    <input type="submit">
</form>